services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # for app communication
      - "15672:15672" # for management UI
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mini-insta-network
  user-mongo:
    image: mongo
    container_name: user-mongo
    ports:
      - "27017:27017"
    volumes:
      - user-data:/data/db # Persist MongoDB data in this volume
    networks:
      - mini-insta-network
  transaction-mongo:
    image: mongo
    container_name: transaction-mongo
    ports:
      - "27018:27017"
    volumes:
      - transaction-data:/data/db # Persist MongoDB data in this volume
    networks:
      - mini-insta-network

  report-mongo:
    image: mongo
    container_name: report-mongo
    ports:
      - "27019:27017"
    volumes:
      - report-data:/data/db # Persist MongoDB data in this volume
    networks:
      - mini-insta-network

  notification-mongo:
    image: mongo
    container_name: notification-mongo
    ports:
      - "27020:27017"
    volumes:
      - notification-data:/data/db # Persist MongoDB data in this volume
    networks:
      - mini-insta-network

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://user-mongo:27017/userdb
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
      user-mongo:
        condition: service_started
    networks:
      - mini-insta-network

  transaction-service:
    build: ./transaction-service
    container_name: transaction-service
    ports:
      - "3002:3002"
    environment:
      - MONGO_URI=mongodb://transaction-mongo:27017/transactiondb
      - RABBITMQ_URL=amqp://rabbitmq
      - JWT_SECRET=your_jwt_secret_key
    depends_on:
      rabbitmq:
        condition: service_healthy
      transaction-mongo:
        condition: service_started
    networks:
      - mini-insta-network

  report-service:
    build: ./report-service
    container_name: report-service
    ports:
      - "3003:3003"
    environment:
      - MONGO_URI=mongodb://report-mongo:27017/reportdb
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
      report-mongo:
        condition: service_started
    networks:
      - mini-insta-network

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "3004:3004"
    environment:
      - MONGO_URI=mongodb://notification-mongo:27017/notificationdb
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
      notification-mongo:
        condition: service_started
    networks:
      - mini-insta-network

networks:
  mini-insta-network:
    driver: bridge
volumes:
  user-data: # Define the volume for user mongo
  transaction-data: # Define the volume for transaction mongo
  report-data: # Define the volume for report mongo
  notification-data: # Define the volume for notification mongo
