version: "3.8"

services:

  user-service:
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
    volumes:
      - ./user-service/src:/app/src # Live code reload
    command: npm run dev # Assumes nodemon

  transaction-service:
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
    volumes:
      - ./transaction-service/src:/app/src
    command: npm run dev

  report-service:
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
    volumes:
      - ./report-service/src:/app/src
    command: npm run dev

  notification-service:
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
    volumes:
      - ./notification-service/src:/app/src
    command: npm run dev

  frontend:
    build:
      context: ./client
      args:
        VITE_MODE: development  # Pass VITE_MODE to Dockerfile