version: "3.8"

services:
  rabbitmq:
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 256M
        reservations:
          cpus: "0.5"
          memory: 128M

  user-mongo:
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 256M
        reservations:
          cpus: "0.5"
          memory: 128M

  transaction-mongo:
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 256M
        reservations:
          cpus: "0.5"
          memory: 128M

  report-mongo:
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 256M
        reservations:
          cpus: "0.5"
          memory: 128M

  notification-mongo:
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 256M
        reservations:
          cpus: "0.5"
          memory: 128M

  user-service:
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=error
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          cpus: "0.2"
          memory: 128M

  transaction-service:
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=error
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          cpus: "0.2"
          memory: 128M

  report-service:
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=error
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          cpus: "0.2"
          memory: 128M

  notification-service:
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=error
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.2"
          memory: 256M

  frontend:
    build:
      context: ./client
      args:
        VITE_MODE: production # or development / production
    environment:
      - NODE_ENV=production
      - VITE_USER_SERVICE_URL=${VITE_USER_SERVICE_URL}
      - VITE_TRANSACTION_SERVICE_URL=${VITE_TRANSACTION_SERVICE_URL}
      - VITE_REPORT_SERVICE_URL=${VITE_REPORT_SERVICE_URL}
      - VITE_NOTIFICATION_SERVICE_URL=${VITE_NOTIFICATION_SERVICE_URL}
