version: "3.8"

services:

  user-service:
    environment:
      - NODE_ENV=staging
      - LOG_LEVEL=error
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          cpus: "0.2"
          memory: 128M

  transaction-service:
    environment:
      - NODE_ENV=staging
      - LOG_LEVEL=error
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          cpus: "0.2"
          memory: 128M

  report-service:
    environment:
      - NODE_ENV=staging
      - LOG_LEVEL=error
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          cpus: "0.2"
          memory: 128M

  notification-service:
    environment:
      - NODE_ENV=staging
      - LOG_LEVEL=error
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          cpus: "0.2"
          memory: 128M
  
  frontend:
    build:
      context: ./client
      args:
       VITE_MODE: staging  # or development / production
    environment:
      - NODE_ENV=staging
      - VITE_USER_SERVICE_URL=${VITE_USER_SERVICE_URL}
      - VITE_TRANSACTION_SERVICE_URL=${VITE_TRANSACTION_SERVICE_URL}
      - VITE_REPORT_SERVICE_URL=${VITE_REPORT_SERVICE_URL}
      - VITE_NOTIFICATION_SERVICE_URL=${VITE_NOTIFICATION_SERVICE_URL}