services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - mini-insta-network

  user-mongo:
    ports:
      - "27017:27017"
    image: mongo
    volumes:
      - user-data:/data/db
    networks:
      - mini-insta-network

  transaction-mongo:
    ports:
      - "27018:27017"
    image: mongo
    volumes:
      - transaction-data:/data/db
    networks:
      - mini-insta-network

  report-mongo:
    ports:
      - "27019:27017"
    image: mongo
    volumes:
      - report-data:/data/db
    networks:
      - mini-insta-network

  notification-mongo:
    ports:
      - "27020:27017"
    image: mongo
    volumes:
      - notification-data:/data/db
    networks:
      - mini-insta-network

  user-service:
    build: ./user-service
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=${MONGO_URI_USER}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - PORT=3001
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      rabbitmq:
        condition: service_healthy
      user-mongo:
        condition: service_started
    networks:
      - mini-insta-network

  transaction-service:
    build: ./transaction-service
    ports:
      - "3002:3002"
    environment:
      - MONGO_URI=${MONGO_URI_TRANSACTION}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=3002
    depends_on:
      rabbitmq:
        condition: service_healthy
      transaction-mongo:
        condition: service_started
    networks:
      - mini-insta-network

  report-service:
    build: ./report-service
    ports:
      - "3003:3003"
    environment:
      - MONGO_URI=${MONGO_URI_REPORT}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - PORT=3003
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      rabbitmq:
        condition: service_healthy
      report-mongo:
        condition: service_started
    networks:
      - mini-insta-network

  notification-service:
    build: ./notification-service
    ports:
      - "3004:3004"
    environment:
      - MONGO_URI=${MONGO_URI_NOTIFICATION}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=3004
    depends_on:
      rabbitmq:
        condition: service_healthy
      notification-mongo:
        condition: service_started
    networks:
      - mini-insta-network

  frontend:
    build:
      context: ./client
    ports:
      - "5173:80"  # Correct port mapping for Vite dev server
    depends_on:
      - user-service
      - transaction-service
      - report-service
      - notification-service
    networks:
      - mini-insta-network
    volumes:
      - ./client:/app  # Live reload for dev environment only, can be overridden for staging/production

        

networks:
  mini-insta-network:
    # driver: bridge

volumes:
  user-data:
  transaction-data:
  report-data:
  notification-data: