version: "3.8"

services:
  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  user-mongo:
    ports:
      - "27017:27017"

  transaction-mongo:
    ports:
      - "27018:27017"

  report-mongo:
    ports:
      - "27019:27017"

  notification-mongo:
    ports:
      - "27020:27017"

  user-service:
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
    volumes:
      - ./user-service/src:/app/src # Live code reload
    command: npm run dev # Assumes nodemon

  transaction-service:
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
    volumes:
      - ./transaction-service/src:/app/src
    command: npm run dev

  report-service:
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
    volumes:
      - ./report-service/src:/app/src
    command: npm run dev

  notification-service:
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
    volumes:
      - ./notification-service/src:/app/src
    command: npm run dev
