apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: your-dockerhub/client-frontend:latest  # ✅ Replace with actual image name
        ports:
        - containerPort: 80
