apiVersion: v1
kind: Secret
metadata:
  name: mongo-secrets
type: Opaque
stringData:
  mongo-user: prod_user
  mongo-pass: prod_pass
  # mongo-uri-user: mongodb://prod_user:prod_pass@user-mongo:27017/userdb?authSource=admin
  mongo-uri-user: mongodb://user-mongo:27017/userdb?authSource=admin
  mongo-uri-transaction: mongodb://transaction-mongo:27017/transactiondb?authSource=admin
  mongo-uri-report: mongodb://report-mongo:27017/reportdb?authSource=admin
  mongo-uri-notification: mongodb://notification-mongo:27017/notificationdb?authSource=admin
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secrets
type: Opaque
stringData:
  rabbitmq-user: guest
  rabbitmq-pass: guest
  rabbitmq-url: amqp://prod_user:prod_pass@rabbitmq:5672
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
stringData:
  jwt-secret: your_jwt_secret_key
